### ISSUE TITLE
admin-server consistently failing to achieve running with error "Add a spring.config.import" =configserver: property to your configuration

### ISSUE THREAD

**Issue by AntonioB-MEC** [Azure-Samples/java-microservices-aks-lab#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Complete Lab 2 to deploy admin-server

### Any log messages given by the failure
>"Add a spring.config.import" =configserver: property to your configuration

### Expected/desired behavior
> admin-server running

### OS and Version?
> Windows 11 Enterprise
### Versions
> 21H2

### Mention any other details that might be useful
Firstly, thank you for this and your work to make this lab. The admin-server is the only component that is not successfully deploying to a Running 1/1 state and the logs report the error. I can accept if this does not repro for you and will go back to hunting for the cause, but hoped you may have some guidance on the topic. Thank you again!  
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vermegi** [comment]
Hi @AntonioB-MEC, thank you for reporting this issue. I am currently working on a next version of the lab where all the starters get updated to spring boot 3 and Java 17. I didn't see the same issue there and I am expecting these changes to be merged into the main branch by end of next week (latest, probably sooner). Would you like to retest with that version? I didn't encounter the same issue there. 

The work in progress on this can be found at https://github.com/vermegi/java-microservices-aks-lab/tree/3.0updates 
But do note that this is very much work in progress and things are likely to change still on this branch. Also note that the steps are not available on github.io yet either, they are in plain .md files in the docs folder.
